### ISSUE TITLE
Version 3.6.5 not working on Paper 1.20.1-19

### ISSUE THREAD

**Issue by Eukon05** [Sytm/waypoints2#98]
This is the output I get:

```[19:23:35 ERROR]: Error occurred while enabling Waypoints v3.6.5 (Is it up to date?)
java.lang.NoClassDefFoundError: de/md5lukas/waypoints/util/MathParser
        at de.md5lukas.waypoints.config.general.TypedTeleportConfiguration.<init>(TeleportConfiguration.kt:54) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.config.general.TeleportConfiguration.<init>(TeleportConfiguration.kt:20) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.config.general.GeneralConfiguration.<init>(GeneralConfiguration.kt:30) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.config.WaypointsConfiguration.<init>(WaypointsConfiguration.kt:14) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.WaypointsPlugin.loadConfiguration(WaypointsPlugin.kt:104) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.WaypointsPlugin.onEnable(WaypointsPlugin.kt:83) ~[waypoints-3.6.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-19]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-19]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.20.1.jar:git-Paper-19]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.20.1.jar:git-Paper-19]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-19]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-19]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-19]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-19]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-19]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: de.md5lukas.waypoints.util.MathParser
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 18 more
```
I've deleted Waypoints files from version 3.6.4 just to be sure, but the same error happens.
I'm using Java 17.

**Comment by Sytm** [comment]
Whyyyyyy. It was working on my pc :(

**Comment by Sytm** [comment]
Okay, for whatever reason the wrong Jar is automatically uploaded which was missing half the plugin :)

Redownload from Modrinth should solve the issue now
